version: "3.7"
# version de la sintaxis de docker

services:
  asesorias-backend-module-proyecto:
    container_name: asesorias-module-proyecto-1
    image: anderlonva/asesorias-module-proyecto:1.0.1
    build:
      context: .
    ports:
      - "4001"
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=4001
    networks:
      - asesorias-app
  
  

  balanceador-carga:
    container_name: balanceador-carga
    image: balanceador-carga:1.0.0
    build:
      context: ./balanceador
    ports:
      - "4003:80"
    networks:
      - asesorias-app

networks:
  asesorias-app:
    driver: bridge


